/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from 'nestjs-i18n';
export type I18nTranslations = {
  app: {
    'FEC-009': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0011': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
  };
  checkout: {
    sale_status_new_arrival: string;
    'checkout.city_is_required': string;
    'checkout.payment_method_is_required': string;
  };
  common: {
    title: string;
    sale_status_sale: string;
    sale_status_coming_soon: string;
    sale_status_new_arrival: string;
  };
  order: {
    'FEC-0001': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0002': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0003': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0004': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0006': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0007': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0008': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0009': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0027': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0040': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
  };
  system: {
    'CUS-0602': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0001': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0002': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0009': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0011': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0012': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0013': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0014': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0034': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'FEC-0035': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
  };
  user: {
    'CUS-0403': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CUS-0405': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0003': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0004': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0005': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0006': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0007': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0008': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0010': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
    'CFO-0015': {
      code_id: string;
      application_code: string;
      title: string;
      prod: string;
      inter: string;
    };
  };
};
export type I18nPath = Path<I18nTranslations>;
